### ISSUE TITLE
sw-select have wrong behavior on single select items

### ISSUE THREAD

**Issue by BlackScorp** [shopware/meteor-component-library#51]
Hello Everyone, there is a bug with sw-select

if you create a list with options where the value is longer than the limit, you will see a box like in multi select with a number

```
const options = [
{
'label':'Option A',
'value':'long text A'
},
{
'label':'Option B',
'value':'long text B'
},

]
```

in this case you will see a number. the problem comes from here

https://github.com/shopware/meteor-component-library/blob/main/src/components/form/sw-select/sw-select.vue#L332

if this.currentValue is an array(mulitselect case) then it should work as expected. but if the this.currentValue is a string this function should return 0

currently i fixed it for me by setting valueLimit=300 then box is not shown anymore

**Comment by htkassner** [comment]
This is solved.
