### ISSUE TITLE
sw-banner bannerIndex not found

### ISSUE THREAD

**Issue by boxblinkracer** [shopware/meteor-component-library#53]
Hi

I'm not quite sure if I do something wrong, or if your component is broken.
When I click on close on the sw-banner, then I get this error from the screenshot.

It basically works as expected, but the console shows an error.

![Screenshot 2023-03-02 at 12 02 59](https://user-images.githubusercontent.com/5579326/222410766-695f2b1e-c3ba-4c9c-9c46-f799cdb15e5e.png)

```
 <sw-banner ... @close="onClose()"
```

```
onClose() {
    ...
},
```

**Comment by htkassner** [comment]
We will check this

**Comment by htkassner** [comment]
Will be fixed with: https://github.com/shopware/meteor-component-library/pull/62
