### ISSUE TITLE
sw-radio component missing

### ISSUE THREAD

**Issue by wannevancamp** [shopware/meteor-component-library#55]
Most basic form elements have been implemented in this library except for the `sw-radio` component. Are these components deliberately unavailable or is it a matter of time?

**Comment by htkassner** [comment]
It is a matter of time. Currently we are busy with a new "grid" which we will call sw-data-table. Maybe the most used component throughout the admin. Further components will be added. We also want to introduce a new wysiwyg editor.

**Comment by htkassner** [comment]
In the meantime you could use the sw-switch-field if it fits your needs.

**Comment by wannevancamp** [comment]
Thanks for the clarification! Looking forward for the new components.
