### ISSUE TITLE
Textfield - Inheritance option seems to be broken

### ISSUE THREAD

**Issue by boxblinkracer** [shopware/meteor-component-library#59]
Hi

so, I've added inheritance options for number fields, toggles and selects,
but for the textfield it just doesnt work.

I click on the lock (to unlock it) but nothing happens.
When I just changed my code from a textfield to a number field it automatically worked.

So I think that textfield component is broken?
can you verify if it really works on your side?

thank you

**Comment by htkassner** [comment]
Hey Christian, we will check this.

**Comment by boxblinkracer** [comment]
perfect, thank you @htkassner
