### ISSUE TITLE
Storybook Data Table

### ISSUE THREAD

**Issue by juliandi01** [shopware/meteor-component-library#82]
Hello everyone,

There is currently a bug in your storybook. If you go to https://shopware.github.io/meteor-component-library/?path=/docs/components-table-and-list-sw-data-table--docs the page loads endlessly and you cannot interact with it.

Is there a way, to fix this bug?

Thank you!

**Comment by Haberkamp** [comment]
Hey, that's an issue on Storybook's side so we cant fix that right now. The good news is that we were able to fix that issue on our Vue 3 version. #81

For now I can offer you a work around. Enter "sw-data-table Default" into the top-left search bar, and click on the first result. That allows you to have a look at the component.
